### ISSUE TITLE
iocage error when updating

### ISSUE THREAD

**Issue by bodems** [freebsd/iocage#20]
I just switched from iocage to iocage-devel and when I try to update a jail with `# iocage update ffbi-www`, I get this:

```
Snapshot: zroot/iocage/jails/ffbi-www@ioc_update_14.1-RELEASE-p3_2024-08-15_15-19-38 created.
Updating jail...

* Updating ffbi-www to the latest patch level... 
Looking up update.FreeBSD.org mirrors... 3 mirrors found.
Fetching metadata signature for 14.1-RELEASE from update2.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.

No updates needed to update system to 14.1-RELEASE-p3.
No updates are available to install.
Run 'tmp4ufwowup [options] fetch' first.
release: 14.1-RELEASE-p3 -> 14.1-RELEASE-p3
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/iocage_cli/update.py", line 45, in cli
    ioc.IOCage(jail=jail, skip_jails=skip_jails).update(pkgs=pkgs)
  File "/usr/local/lib/python3.11/site-packages/iocage_lib/iocage.py", line 1988, in update
    ioc_fetch.IOCFetch(
  File "/usr/local/lib/python3.11/site-packages/iocage_lib/ioc_fetch.py", line 947, in fetch_update
    iocage_lib.ioc_common.consume_and_log(
  File "/usr/local/lib/python3.11/site-packages/iocage_lib/ioc_common.py", line 918, in consume_and_log
    for output in filter(lambda o: any(v for v in o), exec_gen):
  File "/usr/local/lib/python3.11/site-packages/iocage_lib/ioc_exec.py", line 265, in exec_jail
    raise iocage_lib.ioc_exceptions.CommandFailed(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/iocage_lib/ioc_exceptions.py", line 34, in __init__
    collections.Iterable
AttributeError: module 'collections' has no attribute 'Iterable'
```

Indeed the jail is up to date, but this traceback shouldn't happen, right? This happens also on a second server, where I also switched to iocage-devel. The iocage version is 1.6.

**Comment by Defenso-QTH** [comment]
Hello, 

I believe this was fixed in 1.7, see https://github.com/freebsd/iocage/commit/daf84155ac568f12f2a36b7e76384d6147fd3c76.

**Comment by bodems** [comment]
Ahh I see. I'm on the quarterly branch, so I still have 1.6. Is it ok to leave this open until 1.7 or later is in quarterly so I can test this again or should I close it?

**Comment by Defenso-QTH** [comment]
Actually I am also encountering this issue on 1.7. Maybe some references to `collections.Iterable` went unnoticed.

```
# iocage update accounting                            Snapshot: zroot/iocage/jails/accounting@ioc_update_14.1-RELEASE-p4_2024-09-08_05-24-50 created.                                                                       Updating jail...                                                                   * Updating accounting to the latest patch level...                                 Looking up update.FreeBSD.org mirrors... 3 mirrors found.
Fetching metadata signature for 14.1-RELEASE from update1.freebsd.org... done.     Fetching metadata index... done.                                                   Inspecting system... done.                                                         Preparing to download files... done.                                               No updates needed to update system to 14.1-RELEASE-p4.                             No updates are available to install.
Run 'tmppvlxh6ak [options] fetch' first.                                           release: 14.1-RELEASE-p4 -> 14.1-RELEASE-p4                                        Traceback (most recent call last):                                                   File "/usr/local/lib/python3.11/site-packages/iocage_lib/ioc_fetch.py", line 947, in fetch_update                                                                       iocage_lib.ioc_common.consume_and_log(                                           File "/usr/local/lib/python3.11/site-packages/iocage_lib/ioc_common.py", line 918, in consume_and_log                                                                   for output in filter(lambda o: any(v for v in o), exec_gen):                     File "/usr/local/lib/python3.11/site-packages/iocage_lib/ioc_exec.py", line 265, in exec_jail                                                                           raise iocage_lib.ioc_exceptions.CommandFailed(                                 iocage_lib.ioc_exceptions.CommandFailed: [b'', b'']
During handling of the above exception, another exception occurred:                
Traceback (most recent call last):                                                   File "/usr/local/bin/iocage", line 10, in <module>                                   sys.exit(cli())
             ^^^^^                                                                   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__                                                                                    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main     rv = self.invoke(ctx)                                                                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke                                                                                      return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke                                                                                      return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke    return __callback(*args, **kwargs)                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/iocage_cli/update.py", line 45, in cli
    ioc.IOCage(jail=jail, skip_jails=skip_jails).update(pkgs=pkgs)
  File "/usr/local/lib/python3.11/site-packages/iocage_lib/iocage.py", line 1988, in update
    ioc_fetch.IOCFetch(
  File "/usr/local/lib/python3.11/site-packages/iocage_lib/ioc_fetch.py", line 950, in fetch_update
    iocage_lib.ioc_common.logit(
  File "/usr/local/lib/python3.11/site-packages/iocage_lib/ioc_common.py", line 109, in logit
    callback(content, exception)
  File "/usr/local/lib/python3.11/site-packages/iocage_lib/ioc_common.py", line 86, in callback
    collections.Iterable
AttributeError: module 'collections' has no attribute 'Iterable'
```
Sorry it looks like my copy-paste is broken.
